In [14]:
import pandas as pd          
import matplotlib.pyplot as plt  
import seaborn as sns       
import warnings
warnings.filterwarnings('ignore')

In [15]:
df = pd.read_csv('../data/Raw/online_retail_II.csv')  
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [16]:

print(f"Filas: {df.shape[0]:,}")      
print(f"Columnas: {df.shape[1]}")      
print()


print("--- Tipos de datos ---")
print(df.dtypes)
print()

print("--- Valores faltantes por columna ---")
print(df.isnull().sum())

Filas: 1,067,371
Columnas: 8

--- Tipos de datos ---
Invoice            str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
Price          float64
Customer ID    float64
Country            str
dtype: object

--- Valores faltantes por columna ---
Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [17]:
filas_antes = len(df)


df = df.dropna(subset=['Customer ID'])


df = df[df['Quantity'] > 0]


df = df[df['Price'] > 0]


filas_despues = len(df)
print(f"Filas originales:  {filas_antes:,}")
print(f"Filas después de limpiar: {filas_despues:,}")
print(f"Filas eliminadas: {filas_antes - filas_despues:,} ({(filas_antes - filas_despues) / filas_antes * 100:.1f}%)")

Filas originales:  1,067,371
Filas después de limpiar: 805,549
Filas eliminadas: 261,822 (24.5%)

In [18]:

df['TotalVenta'] = df['Quantity'] * df['Price']

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

df['Mes'] = df['InvoiceDate'].dt.month        
df['Anio'] = df['InvoiceDate'].dt.year         
df['DiaSemana'] = df['InvoiceDate'].dt.day_name()
traduccion_dias = {
    'Monday':    'Lunes',
    'Tuesday':   'Martes',
    'Wednesday': 'Miércoles',
    'Thursday':  'Jueves',
    'Friday':    'Viernes',
    'Saturday':  'Sábado',
    'Sunday':    'Domingo'
}
df['DiaSemana'] = df['DiaSemana'].replace(traduccion_dias)

df[['InvoiceDate', 'DiaSemana', 'Quantity', 'Price', 'TotalVenta', 'Mes', 'Anio']].head()

          InvoiceDate DiaSemana  Quantity  Price  TotalVenta  Mes  Anio
0 2009-12-01 07:45:00    Martes        12   6.95        83.4   12  2009
1 2009-12-01 07:45:00    Martes        12   6.75        81.0   12  2009
2 2009-12-01 07:45:00    Martes        12   6.75        81.0   12  2009
3 2009-12-01 07:45:00    Martes        48   2.10       100.8   12  2009
4 2009-12-01 07:45:00    Martes        24   1.25        30.0   12  2009

In [19]:
diccionario_paises = {
    'United Kingdom': 'Reino Unido',
    'Netherlands': 'Países Bajos',
    'EIRE': 'Irlanda',
    'Germany': 'Alemania',
    'France': 'Francia',
    'Australia': 'Australia',
    'Spain': 'España',
    'Switzerland': 'Suiza',
    'Portugal': 'Portugal',
    'Belgium': 'Bélgica',
    'Sweden': 'Suecia',
    'Japan': 'Japón',
    'Norway': 'Noruega',
    'Finland': 'Finlandia',
    'Italy': 'Italia',
    'Cyprus': 'Chipre',
    'Austria': 'Austria',
    'Channel Islands': 'Islas del Canal',
    'Denmark': 'Dinamarca',
    'Greece': 'Grecia',
    'USA': 'Estados Unidos',
    'Poland': 'Polonia',
    'Unspecified': 'No Especificado',
    'United Arab Emirates': 'Emiratos Árabes Unidos',
    'Singapore': 'Singapur',
    'Malta': 'Malta',
    'Lithuania': 'Lituania',
    'Israel': 'Israel',
    'RSA': 'Sudáfrica',
    'Iceland': 'Islandia',
    'Brazil': 'Brasil',
    'Canada': 'Canadá',
    'Korea': 'Corea del Sur',
    'Bahrain': 'Bahréin',
    'Lebanon': 'Líbano',
    'West Indies': 'Indias Occidentales',
    'Thailand': 'Tailandia',
    'Saudi Arabia': 'Arabia Saudita',
    'Czech Republic': 'República Checa',
    'European Community': 'Comunidad Europea',
    'Bermuda': 'Bermudas',
    'Hong Kong': 'Hong Kong',
    'Nigeria': 'Nigeria'
}
df['Country'] = df['Country'].replace(diccionario_paises)

In [20]:
df.to_csv('../data/processed/online_retail_CLEAN.csv', index=False)